#!/bin/sh
# Prevent committing Rust code that produces compiler warnings.
# Enable: git config core.hooksPath .githooks

set -e
cd "$(git rev-parse --show-toplevel)"
export RUSTFLAGS="-D warnings"
cargo check --workspace
exit 0
